# Generated by Django 3.2.22 on 2023-10-19 09:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_unixdatetimefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurbArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('published_date', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('last_updated_date', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'area',
            },
        ),
    ]
